version: '3.8'
services:
  task-manager-db:
    image: postgres:14-alpine
    container_name: taskman_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=effectivemobile
      - POSTGRES_USER=effective
      - POSTGRES_PASSWORD=adminpass

  task-manager-app:
    build: .
    image: taskman_image
    container_name: taskman_container
    ports:
      - "8080:8080"
    depends_on:
      - task-manager-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-manager-db:5432/effectivemobile
      - DB_NAME=effectivemobile
      - POSTGRES_USER=effective
      - POSTGRES_PASSWORD=adminpass
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
