CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL UNIQUE,
    password varchar,
    first_name varchar,
    last_name varchar,
    refresh_token varchar,
    role varchar
);

CREATE TABLE IF NOT EXISTS tasks
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL UNIQUE,
    description varchar(1000),
    status varchar NOT NULL,
    priority varchar NOT NULL,
    creator_id bigint NOT NULL,
    performer_id bigint,
    CONSTRAINT fk_users FOREIGN KEY (creator_id) REFERENCES users (id),
    FOREIGN KEY (performer_id) REFERENCES users (id)
    );

CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment varchar(1000) NOT NULL,
    task_id bigint,
    author_id bigint,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_tasks FOREIGN KEY (task_id) REFERENCES tasks (id)
);




